# Generated by Django 4.0 on 2022-03-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Park',
                'verbose_name_plural': 'Parks',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('A0', 'A0'), ('B0', 'B0'), ('C0', 'C0'), ('D0', 'D0'), ('E0', 'E0'), ('F0', 'F0'), ('G0', 'G0'), ('H0', 'H0'), ('I0', 'I0'), ('J0', 'J0'), ('K0', 'K0'), ('L0', 'L0'), ('M0', 'M0'), ('N0', 'N0'), ('O0', 'O0'), ('P0', 'P0'), ('Q0', 'Q0'), ('R0', 'R0'), ('S0', 'S0'), ('T0', 'T0'), ('U0', 'U0'), ('V0', 'V0'), ('W0', 'W0'), ('X0', 'X0'), ('Y0', 'Y0'), ('Z0', 'Z0'), ('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('D1', 'D1'), ('E1', 'E1'), ('F1', 'F1'), ('G1', 'G1'), ('H1', 'H1'), ('I1', 'I1'), ('J1', 'J1'), ('K1', 'K1'), ('L1', 'L1'), ('M1', 'M1'), ('N1', 'N1'), ('O1', 'O1'), ('P1', 'P1'), ('Q1', 'Q1'), ('R1', 'R1'), ('S1', 'S1'), ('T1', 'T1'), ('U1', 'U1'), ('V1', 'V1'), ('W1', 'W1'), ('X1', 'X1'), ('Y1', 'Y1'), ('Z1', 'Z1'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('D2', 'D2'), ('E2', 'E2'), ('F2', 'F2'), ('G2', 'G2'), ('H2', 'H2'), ('I2', 'I2'), ('J2', 'J2'), ('K2', 'K2'), ('L2', 'L2'), ('M2', 'M2'), ('N2', 'N2'), ('O2', 'O2'), ('P2', 'P2'), ('Q2', 'Q2'), ('R2', 'R2'), ('S2', 'S2'), ('T2', 'T2'), ('U2', 'U2'), ('V2', 'V2'), ('W2', 'W2'), ('X2', 'X2'), ('Y2', 'Y2'), ('Z2', 'Z2'), ('A3', 'A3'), ('B3', 'B3'), ('C3', 'C3'), ('D3', 'D3'), ('E3', 'E3'), ('F3', 'F3'), ('G3', 'G3'), ('H3', 'H3'), ('I3', 'I3'), ('J3', 'J3'), ('K3', 'K3'), ('L3', 'L3'), ('M3', 'M3'), ('N3', 'N3'), ('O3', 'O3'), ('P3', 'P3'), ('Q3', 'Q3'), ('R3', 'R3'), ('S3', 'S3'), ('T3', 'T3'), ('U3', 'U3'), ('V3', 'V3'), ('W3', 'W3'), ('X3', 'X3'), ('Y3', 'Y3'), ('Z3', 'Z3'), ('A4', 'A4'), ('B4', 'B4'), ('C4', 'C4'), ('D4', 'D4'), ('E4', 'E4'), ('F4', 'F4'), ('G4', 'G4'), ('H4', 'H4'), ('I4', 'I4'), ('J4', 'J4'), ('K4', 'K4'), ('L4', 'L4'), ('M4', 'M4'), ('N4', 'N4'), ('O4', 'O4'), ('P4', 'P4'), ('Q4', 'Q4'), ('R4', 'R4'), ('S4', 'S4'), ('T4', 'T4'), ('U4', 'U4'), ('V4', 'V4'), ('W4', 'W4'), ('X4', 'X4'), ('Y4', 'Y4'), ('Z4', 'Z4'), ('A5', 'A5'), ('B5', 'B5'), ('C5', 'C5'), ('D5', 'D5'), ('E5', 'E5'), ('F5', 'F5'), ('G5', 'G5'), ('H5', 'H5'), ('I5', 'I5'), ('J5', 'J5'), ('K5', 'K5'), ('L5', 'L5'), ('M5', 'M5'), ('N5', 'N5'), ('O5', 'O5'), ('P5', 'P5'), ('Q5', 'Q5'), ('R5', 'R5'), ('S5', 'S5'), ('T5', 'T5'), ('U5', 'U5'), ('V5', 'V5'), ('W5', 'W5'), ('X5', 'X5'), ('Y5', 'Y5'), ('Z5', 'Z5'), ('A6', 'A6'), ('B6', 'B6'), ('C6', 'C6'), ('D6', 'D6'), ('E6', 'E6'), ('F6', 'F6'), ('G6', 'G6'), ('H6', 'H6'), ('I6', 'I6'), ('J6', 'J6'), ('K6', 'K6'), ('L6', 'L6'), ('M6', 'M6'), ('N6', 'N6'), ('O6', 'O6'), ('P6', 'P6'), ('Q6', 'Q6'), ('R6', 'R6'), ('S6', 'S6'), ('T6', 'T6'), ('U6', 'U6'), ('V6', 'V6'), ('W6', 'W6'), ('X6', 'X6'), ('Y6', 'Y6'), ('Z6', 'Z6'), ('A7', 'A7'), ('B7', 'B7'), ('C7', 'C7'), ('D7', 'D7'), ('E7', 'E7'), ('F7', 'F7'), ('G7', 'G7'), ('H7', 'H7'), ('I7', 'I7'), ('J7', 'J7'), ('K7', 'K7'), ('L7', 'L7'), ('M7', 'M7'), ('N7', 'N7'), ('O7', 'O7'), ('P7', 'P7'), ('Q7', 'Q7'), ('R7', 'R7'), ('S7', 'S7'), ('T7', 'T7'), ('U7', 'U7'), ('V7', 'V7'), ('W7', 'W7'), ('X7', 'X7'), ('Y7', 'Y7'), ('Z7', 'Z7'), ('A8', 'A8'), ('B8', 'B8'), ('C8', 'C8'), ('D8', 'D8'), ('E8', 'E8'), ('F8', 'F8'), ('G8', 'G8'), ('H8', 'H8'), ('I8', 'I8'), ('J8', 'J8'), ('K8', 'K8'), ('L8', 'L8'), ('M8', 'M8'), ('N8', 'N8'), ('O8', 'O8'), ('P8', 'P8'), ('Q8', 'Q8'), ('R8', 'R8'), ('S8', 'S8'), ('T8', 'T8'), ('U8', 'U8'), ('V8', 'V8'), ('W8', 'W8'), ('X8', 'X8'), ('Y8', 'Y8'), ('Z8', 'Z8'), ('A9', 'A9'), ('B9', 'B9'), ('C9', 'C9'), ('D9', 'D9'), ('E9', 'E9'), ('F9', 'F9'), ('G9', 'G9'), ('H9', 'H9'), ('I9', 'I9'), ('J9', 'J9'), ('K9', 'K9'), ('L9', 'L9'), ('M9', 'M9'), ('N9', 'N9'), ('O9', 'O9'), ('P9', 'P9'), ('Q9', 'Q9'), ('R9', 'R9'), ('S9', 'S9'), ('T9', 'T9'), ('U9', 'U9'), ('V9', 'V9'), ('W9', 'W9'), ('X9', 'X9'), ('Y9', 'Y9'), ('Z9', 'Z9'), ('A10', 'A10'), ('B10', 'B10'), ('C10', 'C10'), ('D10', 'D10'), ('E10', 'E10'), ('F10', 'F10'), ('G10', 'G10'), ('H10', 'H10'), ('I10', 'I10'), ('J10', 'J10'), ('K10', 'K10'), ('L10', 'L10'), ('M10', 'M10'), ('N10', 'N10'), ('O10', 'O10'), ('P10', 'P10'), ('Q10', 'Q10'), ('R10', 'R10'), ('S10', 'S10'), ('T10', 'T10'), ('U10', 'U10'), ('V10', 'V10'), ('W10', 'W10'), ('X10', 'X10'), ('Y10', 'Y10'), ('Z10', 'Z10'), ('A11', 'A11'), ('B11', 'B11'), ('C11', 'C11'), ('D11', 'D11'), ('E11', 'E11'), ('F11', 'F11'), ('G11', 'G11'), ('H11', 'H11'), ('I11', 'I11'), ('J11', 'J11'), ('K11', 'K11'), ('L11', 'L11'), ('M11', 'M11'), ('N11', 'N11'), ('O11', 'O11'), ('P11', 'P11'), ('Q11', 'Q11'), ('R11', 'R11'), ('S11', 'S11'), ('T11', 'T11'), ('U11', 'U11'), ('V11', 'V11'), ('W11', 'W11'), ('X11', 'X11'), ('Y11', 'Y11'), ('Z11', 'Z11'), ('A12', 'A12'), ('B12', 'B12'), ('C12', 'C12'), ('D12', 'D12'), ('E12', 'E12'), ('F12', 'F12'), ('G12', 'G12'), ('H12', 'H12'), ('I12', 'I12'), ('J12', 'J12'), ('K12', 'K12'), ('L12', 'L12'), ('M12', 'M12'), ('N12', 'N12'), ('O12', 'O12'), ('P12', 'P12'), ('Q12', 'Q12'), ('R12', 'R12'), ('S12', 'S12'), ('T12', 'T12'), ('U12', 'U12'), ('V12', 'V12'), ('W12', 'W12'), ('X12', 'X12'), ('Y12', 'Y12'), ('Z12', 'Z12'), ('A13', 'A13'), ('B13', 'B13'), ('C13', 'C13'), ('D13', 'D13'), ('E13', 'E13'), ('F13', 'F13'), ('G13', 'G13'), ('H13', 'H13'), ('I13', 'I13'), ('J13', 'J13'), ('K13', 'K13'), ('L13', 'L13'), ('M13', 'M13'), ('N13', 'N13'), ('O13', 'O13'), ('P13', 'P13'), ('Q13', 'Q13'), ('R13', 'R13'), ('S13', 'S13'), ('T13', 'T13'), ('U13', 'U13'), ('V13', 'V13'), ('W13', 'W13'), ('X13', 'X13'), ('Y13', 'Y13'), ('Z13', 'Z13')], default=1, max_length=256)),
                ('park', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='scope_app.park')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Dino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('species', models.CharField(choices=[('Tyrannosaurus', 'Tyrannosaurus'), ('Velociraptor', 'Velociraptor'), ('Apatosaurus', 'Apatosaurus'), ('Stegosaurus', 'Stegosaurus'), ('Triceratops', 'Triceratops')], max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100)),
                ('digestion_period_in_hours', models.IntegerField(default=48)),
                ('herbivore', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='scope_app.park')),
            ],
            options={
                'verbose_name': 'Dino',
                'verbose_name_plural': 'Dinos',
            },
        ),
    ]
