# Generated by Django 4.0 on 2022-03-04 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scope_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='dino',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scope_app.dino'),
        ),
        migrations.AddField(
            model_name='zone',
            name='last_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
